Repository appuio/component-appuio-cloud, pull requests merged in 2021-09, with the labels that each got.

#8 Add rule to block creation/editing of reserved namespaces
  class/appuio-cloud.yml
  class/defaults.yml
  component/common.libsonnet
  component/main.jsonnet
  component/namespace-policies.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/00_namespace.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_appuio_ns_provisioner_role.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_appuio_ns_provisioners_crb.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
Labels: enhancement

#10 Allow OpenShift to bypass Namespace policies
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
Labels: fix

#9 Add generator rule to create rolebinding in new namespaces
  class/appuio-cloud.yml
  class/defaults.yml
  component/common.libsonnet
  component/generated-rolebindings.jsonnet
  component/namespace-policies.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
Labels: enhancement

#11 Fix rule: Add common ns bypass excludes
  component/namespace-policies.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
Labels: bug

#12 Exempt all (system) clusterroles allowed to edit namespaces from restrictions
  class/defaults.yml
  hack/find-clusterroles.sh
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
Labels: bug

#13 Inject user's default organization when creating namespace without the organization label
  component/namespace-policies.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
Labels: enhancement

#16 Create OCP project template and add organization label to projects
  class/appuio-cloud.yml
  component/namespace-policies.jsonnet
  component/project-template.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/20_project_template.yaml
Labels: enhancement

#14 Use `request.userInfo.groups` to validate the organization label
  component/namespace-policies.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
Labels: change

#17 Use recommended syntax for Kyverno match and exclude configurations
  component/common.libsonnet
  component/generated-rolebindings.jsonnet
  component/namespace-policies.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
Labels: change

#15 Add ResourceQuota and LimitRange to Org Namespace
  class/appuio-cloud.yml
  class/defaults.yml
  component/common.libsonnet
  component/generated-rolebindings.jsonnet
  component/quota-limitrange.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Labels: enhancement

#18 Update CPU/Mem resource quotas
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Labels: change

#19 Introduce ephemeral-storage quotas
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Labels: change

#20 Add policy to deny Project creation if requesting user has no default organization
  class/appuio-cloud.yml
  component/common.libsonnet
  component/project-policies.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml
Labels: enhancement
