Repository appuio/component-appuio-cloud, pull requests merged in 2021-11, with the labels that each got.

#30 Split resource quotas into `objects`, `compute` and `compute-terminating`
  class/defaults.yml
  component/quota-limitrange.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Labels: enhancement

#31 Use Gi in Memory Max LimitRange instead of G
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Labels: bug

#32 Use same values as on APPUiO Public for terminating compute quota
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Labels: ignore

#33 Add a clusterpolicy to set default for `.spec.activeDeadlineSeconds`
  class/appuio-cloud.yml
  class/defaults.yml
  component/runonce-activedeadlineseconds.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/30_set_runonce_activedeadlineseconds.yaml
Labels: enhancement

#34 Enable namespace transfer
  class/defaults.yml
  component/generated-rolebindings.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
Labels: enhancement

#35 Add option to override resource-quota defaults per namespace
  component/quota-limitrange.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Labels: enhancement

#37 Namespace label validation rules
  .gitignore
  .sync.yml
  Makefile
  Makefile.kyverno.mk
  class/defaults.yml
  component/common.libsonnet
  component/namespace-policies.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
  tests/kyverno/defaults/validate-namespace-metadata-test.yaml
  tests/kyverno/defaults/validate-namespace-metadata-variables.yaml
  tests/kyverno/defaults/validate-namespace-metadata/auxiliary-annotation.yaml
  tests/kyverno/defaults/validate-namespace-metadata/auxiliary-label.yaml
  tests/kyverno/defaults/validate-namespace-metadata/delete-existing-auxiliary-annotation.yaml
  tests/kyverno/defaults/validate-namespace-metadata/delete-existing-auxiliary-label.yaml
  tests/kyverno/defaults/validate-namespace-metadata/ignore-existing-auxiliary-annotation.yaml
  tests/kyverno/defaults/validate-namespace-metadata/ignore-existing-auxiliary-label.yaml
  tests/kyverno/defaults/validate-namespace-metadata/no-annotations.yaml
  tests/kyverno/defaults/validate-namespace-metadata/no-labels.yaml
  tests/kyverno/defaults/validate-namespace-metadata/null-annotations.yaml
  tests/kyverno/defaults/validate-namespace-metadata/null-labels.yaml
  tests/kyverno/defaults/validate-namespace-metadata/update-existing-auxiliary-annotation.yaml
  tests/kyverno/defaults/validate-namespace-metadata/update-existing-auxiliary-label.yaml
  tests/kyverno/defaults/validate-namespace-metadata/whitelisted-and-auxiliary-annotations.yaml
  tests/kyverno/defaults/validate-namespace-metadata/whitelisted-and-auxiliary-labels.yaml
  tests/kyverno/defaults/validate-namespace-metadata/whitelisted-annotation.yaml
  tests/kyverno/defaults/validate-namespace-metadata/whitelisted-label.yaml
Labels: enhancement

#39 Change default namespace
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/00_namespace.yaml
Labels: change

#40 Make namespace validation easier to debug
  component/namespace-policies.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
Labels: enhancement

#42 Ignore Kyverno mutate debug annotation
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
Labels: bug

#41 Add Cilium to the list of reserved namespaces
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
Labels: change

#38 Add namespace quota per zone policy
  class/appuio-cloud.yml
  class/defaults.yml
  component/common.libsonnet
  component/namespace-quota.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/13_namespace_quota_overrides.yaml
Labels: enhancement

#43 Allow network policy labels to be edited by users
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
Labels: change

#44 Add create precondition to namespace quota policy
  component/namespace-quota.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
Labels: bug

#47 Allow user to delete namespaces he owns
  component/generated-rolebindings.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
Labels: enhancement

#48 Add CODEOWNERS file
  CODEOWNERS
Labels: change

#50 Raise default CPU requests and limits for NotTerminating resources
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Labels: bug

#45 Update default terminating quota to match APPUiO Public
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Labels: change

#49 Unify default RoleBinding of namespaces and projects
  class/defaults.yml
  component/common.libsonnet
  component/generated-rolebindings.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/20_project_template.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns-test.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns-variables.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns/init-rolebinding.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns/uninit-rolebinding-patched.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns/uninit-rolebinding.yaml
Labels: change
