Repository appuio/component-appuio-cloud, pull requests merged in 2022-11, with the labels that each got.

#130 Add support for SSH URL to the policy doc generator
  tools/render/git.go
Labels: ignore

#129 Replace kyverno rolebinding policies with cloud agent
  class/appuio-cloud.yml
  class/defaults.yml
  component/agent.jsonnet
  component/cluster-roles.jsonnet
  component/generated-rolebindings.jsonnet
  docs/modules/ROOT/pages/explanations/policies.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/references/policies/10_generate_default_rolebinding_in_ns.adoc
  docs/modules/ROOT/pages/references/policies/index.adoc
  docs/modules/ROOT/partials/nav-policy.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_default_org_role_binding.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_role.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/10_additional_clusterroles.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns-test.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns-variables.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns/init-rolebinding.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns/uninit-rolebinding-patched.yaml
  tests/kyverno/defaults/generate-default-rolebinding-in-ns/uninit-rolebinding.yaml
Labels: change

#133 Make APPUiO Cloud Agent resource requests and limits configurable
  class/defaults.yml
  component/agent.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: enhancement

#134 Update kyverno policies to work with version 1.8.0
  component/common.libsonnet
  component/namespace-policies.jsonnet
  component/namespace-quota.jsonnet
  component/project-policies.jsonnet
  docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc
  docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc
  docs/modules/ROOT/pages/references/policies/02_organization_projects.adoc
  docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc
  docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc
  docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc
  docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_projects.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
Labels: bug

#135 Add clusterrole appuio:metrics-viewer
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/10_additional_clusterroles.yaml
Labels: enhancement

#136 Update dependency ghcr.io/appuio/appuio-cloud-agent to v0.8.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency
