Repository appuio/component-appuio-cloud, pull requests merged in 2022-10, with the labels that each got.

#120 Switch to subject instead of clusterrole for resource locker
  class/defaults.yml
  docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc
  docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc
  docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc
  docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc
  docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc
  docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
Labels: bug

#119 Agent with node selector validation
  class/defaults.yml
  component/agent.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_role.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/10_webhook_config.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
Labels: enhancement

#123 Update dependency ghcr.io/appuio/appuio-cloud-agent to v0.6.1
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency

#125 Fix patch for disallowing docker builds
  component/build-strategy.jsonnet
  tests/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/15_disallow_docker_build_strategy_patch.yaml
Labels: bug
