Repository appuio/component-appuio-cloud, pull requests merged in 2023-07, with the labels that each got.

#163 Update component to use `patch-operator.libsonnet` directly
  .cruft.json
  component/build-strategy.jsonnet
  tests/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/15_disallow_docker_build_strategy_patch.yaml
Labels: dependency

#164 Support scheduling Cloud Agent on master nodes
  class/defaults.yml
  component/agent.jsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: enhancement

#165 Only install `ZoneUsageProfile` CRD if the agent image tag is >= v0.10.0
  component/agent.jsonnet
Labels: bug

#166 Allow removing appuio-cloud-agent config entries by setting them to `null`
  component/agent.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: bug
