Repository appuio/component-appuio-cloud, pull requests merged in 2024-09, with the labels that each got.

#202 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.18.0
  class/defaults.yml
  component/agent.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/10_webhook_config.yaml
Labels: dependency

#203 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.18.1
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency

#204 Implement ResourceQuota and LimitRange generation in agent
  class/defaults.yml
  component/agent.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/10_webhook_config.yaml
Labels: enhancement, bump:minor

#206 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.19.1
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency

#208 Re-add namespace self provisioning
  component/main.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_appuio_ns_provisioner_role.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_appuio_ns_provisioners_crb.yaml
Labels: bug, bump:patch

#209 Adjust LimitRange minimum CPU request to `1m`
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: enhancement, bump:minor
