Repository appuio/component-appuio-cloud, pull requests merged in 2024-08, with the labels that each got.

#192 Update `actions/setup-go` to `v5` to get a go dep cache
  .github/workflows/test.custom.yaml
Labels: dependency

#191 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.16.0
  class/defaults.yml
  component/agent.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/00_crds/cloudagent.appuio.io_zoneusageprofiles.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_role.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/10_webhook_config.yaml
Labels: dependency

#193 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.16.1
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency

#194 Allow to generically disable Kyverno policies
  class/appuio-cloud.yml
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  postprocess/disable-kyveno-policies.jsonnet
Labels: enhancement

#195 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.17.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency

#196 Inject legacy namespace quota into agent config
  class/defaults.yml
  docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc
  tests/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
Labels: change

#197 Remove empty objects from policy filter
  class/appuio-cloud.yml
  component/common.libsonnet
  component/namespace-policies.jsonnet
  component/namespace-quota.jsonnet
  component/quota-limitrange.jsonnet
  component/runonce-activedeadlineseconds.jsonnet
  postprocess/disable-kyveno-policies.jsonnet
Labels: bug

#198 Don't inject `namespaceSelector` for namespace and project validating webhooks
  component/agent.jsonnet
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/10_webhook_config.yaml
Labels: bug

#199 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.17.1
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency

#200 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.17.2
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency

#201 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.17.3
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency, bump:patch
