Repository appuio/component-appuio-cloud, pull requests merged in 2024-07, with the labels that each got.

#187 Allow Cloudscale CCM to set LB service labels
  class/defaults.yml
  docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc
  docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc
  docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc
  docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc
  docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
Labels: change

#186 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.14.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/00_crds/cloudagent.appuio.io_zoneusageprofiles.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/10_webhook_config.yaml
Labels: dependency, bump:minor

#188 Update ghcr.io/appuio/appuio-cloud-agent Docker tag to v0.15.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Labels: dependency
